# Generated by Django 5.0.2 on 2024-02-26 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='sexo',
            field=models.CharField(default=2, max_length=50, verbose_name='sexo'),
            preserve_default=False,
        ),
    ]
