# Generated by Django 5.0.2 on 2024-02-26 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='tipo',
            table='tipo',
        ),
    ]
