# Generated by Django 5.0.2 on 2024-02-26 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0002_empleado_sexo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empleado',
            name='sexo',
        ),
    ]
